# Settings --------------------------------------------------------------------
theme = "nord-deep"

[editor]
# bufferline = "multiple"
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "disable"
line-number = "relative"
popup-border = "all"
rulers = [80, 120]
shell = ["zsh", "-c"]
trim-trailing-whitespace = true
true-color = true
default-yank-register = "+"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
prefix-len = 2

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.file-picker]
hidden = true

[editor.whitespace.render]
nbsp = "all"
nnbsp = "all"
tab = "all"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["file-name"]
right = [
  "file-type",
  "file-encoding",
  "diagnostics",
  "position-percentage",
  "position",
]

# Keybindings -----------------------------------------------------------------

[keys.normal]
# No more fighting with the cursor!
esc = ["collapse_selection", "keep_primary_selection"]

# Nice to have
"C-," = ":config-open"
"C-r" = ":config-reload"
"C-w" = { x = ":buffer-close", X = ":buffer-close!", n = { n = ":new" } }
"Meta-/" = "toggle_comments"
"Meta-A-j" = ["copy_selection_on_next_line"]
"Meta-A-k" = ["copy_selection_on_prev_line"]
"Meta-o" = "file_explorer"
"Meta-p" = "file_picker"
"Meta-R" = ":reload-all"
"Meta-s" = ":write"
"Meta-S-j" = ["extend_to_file_end"]
"Meta-S-k" = ["extend_to_file_start"]
"Meta-z" = ["undo", "collapse_selection"]
"Meta-Z" = ["redo", "collapse_selection"]
"S-A-j" = [
  "extend_to_line_bounds",
  "yank",
  "paste_clipboard_after",
  "collapse_selection",
]
"S-A-k" = [
  "extend_to_line_bounds",
  "yank",
  "paste_clipboard_before",
  "collapse_selection",
]

# Vim-like
"$" = "goto_line_end"
"%" = "match_brackets"
"[" = { b = "goto_previous_buffer" }
"]" = { b = "goto_next_buffer" }
"^" = "goto_first_nonwhitespace"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
D = ["select_mode", "extend_to_line_end", "yank", "delete_selection"]
G = "goto_file_end"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
u = ["undo", "collapse_selection"]
U = ["redo", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]
Y = ["select_mode", "extend_to_line_end", "yank", "collapse_selection"]
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]

[keys.normal.space]
n = ":new"
q = ":quit"
Q = ":quit!"
R = ":reload-all"
w = ":write"
W = ":write-all"
x = ":buffer-close"
X = ":buffer-close!"

[keys.insert]
# No more fighting with the cursor!
esc = ["collapse_selection", "normal_mode"]

# Nice to have
"Meta-o" = "file_explorer"
"Meta-p" = "file_picker"
"Meta-z" = ["undo", "collapse_selection"]
"Meta-Z" = ["redo", "collapse_selection"]

[keys.select]
# No more fighting with the cursor!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Nice to have
"Meta-/" = "toggle_comments"

# Vim-like
"$" = "goto_line_end"
"%" = "match_brackets"
"^" = "goto_first_nonwhitespace"
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
G = ["extend_to_file_end"]
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
y = ["yank", "flip_selections", "collapse_selection", "normal_mode"]
