theme = "nord-deep"

[editor]
cursorline = true
color-modes = true
rulers = [80, 120]
completion-replace = true
bufferline = "multiple"
# line-number = "relative"
shell = ["zsh", "-c"]
trim-trailing-whitespace = true
popup-border = "all"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = true

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"
