# Nord Deep theme for Helix
# An arctic, north-bluish color palette taken to deeper depths

# Syntax highlighting ---------------------------------------------------------

"attribute" = "nord-text"

"boolean" = "nord-blue"

"type" = "nord-aqua"
"type.builtin" = "nord-aqua"
"type.enum.variant" = "nord-aqua"
"type.parameter" = "nord-aqua"

"constructor" = "nord-aqua"

"constant" = "nord-text"
"constant.builtin" = "nord-blue"
"constant.language" = "nord-blue"
"constant.character" = "nord-yellow"
"constant.numeric" = "nord-magenta"

"string" = "nord-green"
"string.regexp" = "nord-yellow"
"string.special" = "nord-green"
"string.special.url" = "nord-cyan"

"comment" = "nord-dim"

"variable" = "nord-text"
"variable.builtin" = "nord-text"
"variable.other.member" = "nord-aqua"
"variable.other.member.private" = { fg = "nord-text", modifiers = ["italic"] }
"variable.parameter" = "nord-text"

"label" = "nord-blue"

"operator" = "nord-blue"

"function" = "nord-cyan"
"function.builtin" = "nord-cyan"
"function.macro" = "nord-cyan"
"function.method" = "nord-cyan"
"function.method.private" = { fg = "nord-cyan", modifiers = ["italic"] }
"function.special" = "nord-cyan"

"tag" = "nord-blue"
"tag.builtin" = "nord-blue"

"punctuation" = "nord-text"
"punctuation.bracket" = "nord-blue"
"punctuation.delimiter" = "nord-blue"
"punctuation.special" = "nord-blue"

"keyword" = "nord-blue"
"keyword.control" = "nord-blue"
"keyword.directive" = "nord-blue"
"keyword.function" = "nord-blue"
"keyword.operator" = "nord-blue"
"keyword.storage" = "nord-blue"

"namespace" = "nord-text"

"special" = "nord-cyan"

"diff.delta" = "nord-yellow"
"diff.minus" = "nord-red"
"diff.plus" = "nord-green"

"markup.heading.1" = "nord-red"
"markup.heading.2" = "nord-orange"
"markup.heading.3" = "nord-yellow"
"markup.heading.4" = "nord-green"
"markup.heading.5" = "nord-cyan"
"markup.heading.6" = "nord-blue"
"markup.bold" = { fg = "nord-text", modifiers = ["bold"] }
"markup.italic" = { fg = "nord-text", modifiers = ["italic"] }
"markup.link.label" = { fg = "nord-cyan", modifiers = ["underlined"] }
"markup.link.text" = "nord-cyan"
"markup.link.url" = { fg = "nord-cyan", modifiers = ["underlined"] }
"markup.list" = "nord-text"
"markup.list.checked" = "nord-green"
"markup.list.unchecked" = "nord-subtle"
"markup.quote" = "nord-magenta"
"markup.raw" = "nord-aqua"
"markup.strikethrough" = { fg = "nord-text", modifiers = ["crossed_out"] }

# UI --------------------------------------------------------------------------

"ui.background" = { fg = "nord-text", bg = "nord-base" }
"ui.background.separator" = { fg = "nord-text" }

"ui.linenr" = { fg = "nord-subtle" }
"ui.linenr.selected" = { fg = "nord-text" }

"ui.statusline" = { fg = "nord-text", bg = "nord-elevated" }
"ui.statusline.inactive" = { fg = "nord-dim", bg = "nord-surface" }
"ui.statusline.insert" = { fg = "nord-base", bg = "nord-cyan" }
"ui.statusline.normal" = { fg = "nord-base", bg = "nord-text" }
"ui.statusline.select" = { fg = "nord-base", bg = "nord-aqua" }
"ui.statusline.separator" = { fg = "nord-text" }

"ui.menu" = { fg = "nord-text", bg = "nord-base" }
"ui.menu.scroll" = { fg = "nord-subtle" }
"ui.menu.selected" = { fg = "nord-cyan", bg = "nord-elevated" }

"ui.popup" = { fg = "nord-dim", bg = "nord-base" }
"ui.popup.info" = { fg = "nord-dim", bg = "nord-base" }

"ui.help" = { fg = "nord-dim", bg = "nord-base" }
"ui.window" = { fg = "nord-elevated" }

"ui.bufferline" = { fg = "nord-dim", bg = "nord-surface" }
"ui.bufferline.active" = { fg = "nord-text", bg = "nord-base" }
"ui.bufferline.background" = { bg = "nord-surface" }

"ui.text" = "nord-text"
"ui.text.directory" = { fg = "nord-blue" }
"ui.text.focus" = { fg = "nord-text", bg = "nord-elevated" }
"ui.text.inactive" = { fg = "nord-dim" }
"ui.text.info" = { fg = "nord-text" }

"ui.virtual" = "nord-dim"
"ui.virtual.indent-guide" = "nord-elevated"
"ui.virtual.inlay-hint" = { fg = "nord-dim", modifiers = ["italic"] }
"ui.virtual.inlay-hint.parameter" = { fg = "nord-dim", modifiers = ["italic"] }
"ui.virtual.inlay-hint.type" = { fg = "nord-dim", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "nord-cyan", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "nord-cursorline" }
"ui.virtual.wrap" = "nord-dim"

"ui.cursor" = { bg = "nord-elevated" }
"ui.cursor.primary" = { fg = "nord-base", bg = "nord-text" }
"ui.cursor.match" = { fg = "nord-orange", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "nord-base", bg = "nord-text" }
"ui.cursor.primary.insert" = { fg = "nord-base", bg = "nord-text" }
"ui.cursor.primary.select" = { fg = "nord-base", bg = "nord-text" }

"ui.cursor.normal" = { fg = "nord-base", bg = "nord-dim" }
"ui.cursor.insert" = { fg = "nord-base", bg = "nord-dim" }
"ui.cursor.select" = { fg = "nord-base", bg = "nord-dim" }

"ui.cursorcolumn.primary" = { bg = "nord-surface" }
"ui.cursorcolumn.secondary" = { bg = "nord-surface" }

"ui.cursorline.primary" = { bg = "nord-cursorline" }
"ui.cursorline.secondary" = { bg = "nord-cursorline" }

"ui.selection" = { bg = "nord-elevated" }
"ui.selection.primary" = { bg = "nord-elevated" }

"ui.highlight" = { bg = "nord-elevated" }

"ui.picker.header" = { fg = "nord-text", modifiers = ["bold"] }
"ui.picker.header.column" = { fg = "nord-text", modifiers = ["bold"] }
"ui.picker.header.column.active" = { fg = "nord-cyan", modifiers = ["bold"] }

"ui.gutter" = { fg = "nord-subtle" }
"ui.gutter.selected" = { fg = "nord-text" }

"diagnostic.deprecated" = { fg = "nord-dim", modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "nord-red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "nord-navy", style = "curl" } }
"diagnostic.info" = { underline = { color = "nord-navy", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "nord-yellow", style = "curl" } }

error = { fg = "nord-red", modifiers = ["italic"] }
warning = { fg = "nord-yellow", modifiers = ["italic"] }
info = { fg = "nord-navy", modifiers = ["italic"] }
hint = { fg = "nord-navy", modifiers = ["italic"] }

[palette]
nord-base = "#212732"
nord-surface = "#2e3440"
nord-elevated = "#3b4252"
nord-subtle = "#434c5e"
nord-dim = "#798094"
nord-text = "#b8c5d1"
nord-bright = "#d4dce6"
nord-aqua = "#8fbcbb"
nord-cyan = "#88c0d0"
nord-blue = "#81a1c1"
nord-navy = "#5e81ac"
nord-red = "#bf616a"
nord-orange = "#d08770"
nord-yellow = "#ebcb8b"
nord-green = "#a3be8c"
nord-magenta = "#b48ead"

# Additional colors
nord-cursorline = "#282e39" # nord-surface 50% over base - for subtle guides
